# src/main/resources/application.yml
server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dongli_db
    username: root
    password: wu123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true